###
POST http://localhost:3000/register
Content-Type: application/json

{
    "username": "ankit",
    "password": "password",
    "email": "ankit@email.com"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "ankit",
    "password": "password1"
}